#!/bin/bash
#+--------------------------------------------------------------------------+
#
# This code is shipped under the Artistic License 2.0. See the file
# Artistic-License-2.0.txt or http://opensource.org/licenses/Artistic-2.0
#
#+--------------------------------------------------------------------------+
#
# onecons - show console data for one user ID 
# Sample URL:  cdlengzs0102.example.com/ldap/onecons?TCPIP&ZS01
#
#+--------------------------------------------------------------------------+
# global variables:
userID=`echo $QUERY_STRING | awk -F'&' '{print $1}'`   # user ID is arg 1 
systemID=`echo $QUERY_STRING | awk -F'&' '{print $2}'` # system ID is arg 2
option=`echo $QUERY_STRING | awk -F'&' '{print $3}'`   # option such as spool 
title="Console of $userID at $systemID"    # page title

# main()
source consuifuncs                         # import common Web UI functions
setWebUIvars                               # override defaults with user's preferences
startPage                                  # start the Web page
cat consolez.css                           # inline consolez cascading style sheets
setRole                                    # set user's role based on login credentials
showOneConsole $userID $systemID $option   # do the work 
drawButtons                                # add buttons at bottom

