#!/bin/bash
#
# This code is shipped under the Artistic License 2.0. See the file
# Artistic-License-2.0.txt or http://opensource.org/licenses/Artistic-2.0
#
#+--------------------------------------------------------------------------+
#
# searchcons - Draw a page that enables the searching of consoles 
#
#---------------------------------------------------------------------------
function headerRow
# create a table header row that spans columns and writes a title in large font
# Arg 1:    number of columns to span
# Args 2-n: title
#---------------------------------------------------------------------------
 {
  local cols=$1                            # arg 1
  shift                                    # get to remaining args
  local text=$@                            # set the title

  if [ "$cols" = 1 ]; then                 # no need for colspan
    echo "<tr><th style=\"background-color:$color3;\"><font size=\"+1\">"
  else
    echo "<tr><th style=\"background-color:$color3;\" colspan=\"$cols\"><font size=\"+1\">"
  fi
  echo "$text</font></th></tr>"            # add text, end font, header and row
 }                                         # headerRow()

#+--------------------------------------------------------------------------+
function drawClearButton
# Draw a button to clear all search filters 
# Args: none
#+--------------------------------------------------------------------------+
 {
  echo "<tr>" 
  echo "<td style=\"text-align:center\"; colspan=\"3\">"
  echo '<form method=GET action="/ldap/searchcons" accept-charset=utf-8>'
  echo "<input class=button type=submit style=\"background-color:$color1\"; value=\"Clear filters\">&nbsp;"
  if [ ${#userIDflt} != 0 ]; then
    echo "<input type=hidden name=hostFlt value=\"\">"
  fi
  if [ ${#systemIDflt} != 0 ]; then
    echo "<input type=hidden name=systemIDflt value=\"\">"
  fi
  if [ ${#}attern} != 0 ]; then
    echo "<input type=hidden name=pattern value=\"\">"
  fi
  echo "</form></td></tr>"  
 }                                         # drawClearButton()

#+--------------------------------------------------------------------------+
function drawMainTable
# Draw a table with search criteria for user ID, system ID/environment 
#   the text patter to search form and a 'Search consoles' button
# Args: none 
#+--------------------------------------------------------------------------+
 {
  startPage $title                         # start the Web page
  cat consolez.css                         # inline cascading style sheets

  if [ ${#pattern} != 0 ]; then 
    pattern=`uudecode $pattern`            # uu-decode the string
  fi

  # draw table with the search criteria
  echo "<h2>$title</h2>"
  echo "<h4 align=center>Enter a search pattern - Blank User ID/SystemID/Environmnent means search all</h4>"
  echo '<table class="consolezTable" align=center>'         # leave room, start table and row
  headerRow 3 Search filters               # first header row

  # row 1
  drawClearButton                          # draw a button to clear filters

  # row 2 - start the form to run searchcons again with filters
  echo "<tr><form method=GET action=/ldap/searchcons accept-charset=utf-8>"
  echo "<td>User ID</td>"
  echo "<td><input type=text id=userIDflt name=userIDflt value=\"$userIDflt\"></td>"
  echo "<td></td>"                         # empty cell
  echo "</tr><tr>"                         # end row, start row

  # row 3
  echo "<td>System ID/Environment</td>"
  echo "<td><input type=text id=systemIDflt name=systemIDflt value=\"$systemIDflt\"></td>"
  echo "<td></td>"                         # empty cell
  echo "</tr><tr>"                         # end row, start row

  # row 4
  echo "<td>Search pattern</td>"
  echo "<td><input type=text id=pattern name=pattern value=\"$pattern\"></td>"
  echo '<td><input type="radio" name="nocase" id="nocase" value="yes">Case insensitive</td>'
  echo "</tr><tr>"                         # end row, start row

  # row 5
  echo '<td align=center colspan="3">'
  echo "<input class=button type=submit style=\"background-color:#8CFF66; font:bold 16px\" value=\"Search consoles\">&nbsp;"
  echo "</form>"                           # end form
  echo "</td></tr></table><br>"            # end cell, row, table, leave some room

  # perform the search
  if [ ${#pattern} != 0 ]; then            # there is a search pattern
    echo '<table class="greenScreenTable">'  # start a 'green screen' table 
    echo "<tr><td><pre>"                   # start row, cell, preformatted text
    if [ ${#userIDflt} = 0 ]; then         # no user ID search criteria
      userIDflt=':'                        # default is all
    fi
    if [ ${#systemIDflt} = 0 ]; then       # no user ID search criteria
      systemIDflt=':'                      # default is all
    fi
    if [ ${#pattern} = 0 ]; then           # no pattern found
      echo "A search pattern must be supplied"
    else
      local args="-w $USER $userIDflt $systemIDflt $pattern"
      if [ "$nocase" = yes ]; then         # case insensitive search
        args="-i $args"                    # add -i arg to grepcons
      fi
      local cmd="/usr/local/sbin/grepcons $args" # command to send
      echo "Searching with: $cmd"
      $cmd                                 # run the command
    fi
  fi
  echo "</td></tr></table><br>"            # end cell, row, table, leave some room
 }                                         # drawMainTable()

#+--------------------------------------------------------------------------+
# global variables
userIDflt=`echo "$QUERY_STRING" | sed -n 's/^.*userIDflt=\([^&]*\).*$/\1/p'`
systemIDflt=`echo "$QUERY_STRING" | sed -n 's/^.*systemIDflt=\([^&]*\).*$/\1/p'`
pattern=`echo "$QUERY_STRING" | sed -n 's/^.*pattern=\([^&]*\).*$/\1/p'`
nocase=`echo "$QUERY_STRING" | sed -n 's/^.*nocase=\([^&]*\).*$/\1/p'`
title="Search z/VM consoles"               # page title

# main()
source /usr/local/sbin/consfuncs           # import common line command functions
source consuifuncs                         # import common Web UI functions
setRole                                    # set user's role based on login credentials
drawMainTable                              # show table with all user IDs that have data 
drawButtons                                # add custom navigation buttons

